services:
  - type: web
    name: everybody.gives
    env: node
    plan: free
    region: frankfurt
    buildCommand: yarn --frozen-lockfile --prod=false &&
      blitz prisma generate &&
      blitz build &&
      blitz prisma migrate deploy
    startCommand: blitz start -p ${PORT}
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: everybody.gives
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: everybody.gives
    region: frankfurt
    plan: free
